// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RAPI_EmpManage.Models;

namespace RAPI_EmpManage.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20220907102753_Mig_EmpManage")]
    partial class Mig_EmpManage
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CLib_MEmp.MDep", b =>
                {
                    b.Property<int>("DepID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DepName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DepID");

                    b.ToTable("DbS_MDep");

                    b.HasData(
                        new
                        {
                            DepID = 1,
                            DepName = "IT"
                        },
                        new
                        {
                            DepID = 2,
                            DepName = "PayRoll"
                        },
                        new
                        {
                            DepID = 3,
                            DepName = "HR"
                        });
                });

            modelBuilder.Entity("CLib_MEmp.MEmp", b =>
                {
                    b.Property<int>("EmpID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DOBirth")
                        .HasColumnType("datetime2");

                    b.Property<int>("DeptID")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GenderSex")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhotoPath")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmpID");

                    b.ToTable("DbS_MEmp");

                    b.HasData(
                        new
                        {
                            EmpID = 1,
                            DOBirth = new DateTime(1977, 5, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeptID = 1,
                            Email = "Samy.Hanna@PBTech.com",
                            FirstName = "Samy",
                            GenderSex = 0,
                            LastName = "Hanna",
                            PhotoPath = "Images/Emp_Samy.png"
                        },
                        new
                        {
                            EmpID = 2,
                            DOBirth = new DateTime(1987, 8, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeptID = 2,
                            Email = "Etve.Samy@PBTech.com",
                            FirstName = "Etve",
                            GenderSex = 1,
                            LastName = "Samy",
                            PhotoPath = "Images/Emp_Etve.png"
                        },
                        new
                        {
                            EmpID = 3,
                            DOBirth = new DateTime(1997, 10, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeptID = 3,
                            Email = "Parthy.Pisho@PBTech.com",
                            FirstName = "Parthy",
                            GenderSex = 1,
                            LastName = "Pisho",
                            PhotoPath = "Images/Emp_Parthy.png"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
